# align_matrix = false
# import_to_using = false
# pipe_to_function_call = false
# short_to_long_function_def = false
align_assignment = true
align_conditional = true
align_pair_arrow = true
align_struct_field = true
always_for_in = true
always_use_return = true
annotate_untyped_fields_with_any = false
conditional_to_if = true
format_docstrings = true
indent = 4
join_lines_based_on_source = true
margin=1500
normalize_line_endings = "auto"
remove_extra_newlines = true
trailing_comma = true
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
whitespace_typedefs = true
